import { Learner, PracticeQuestion, WorldStage, Badge } from './types';

// Default active student for demo
export const MOCK_ACTIVE_STUDENT: Learner = {
  id: 'learner-001',
  name: 'Aarav Kumar',
  grade: 3,
  classroomId: 'class-3a',
  avatar: '🌱',
  xp: 450,
  streakDays: 5,
  currentQuest: 'Master Connected Text Reading',
  readingLevel: 'paragraph',
  numeracyLevel: 'subtraction',
  profile: {
    learnerId: 'learner-001',
    letterRecognition: 'demonstrated',
    wordReading: 'demonstrated',
    paragraphReading: 'developing',
    storyReading: 'needs_support',
    comprehension: 'needs_support',
    numberRecognition1_9: 'demonstrated',
    numberRecognition11_99: 'demonstrated',
    subtraction: 'developing',
    division: 'needs_support',
    confidence: {
      letterRecognition: 98,
      wordReading: 92,
      paragraphReading: 72,
      storyReading: 35,
      comprehension: 40,
      numberRecognition1_9: 99,
      numberRecognition11_99: 94,
      subtraction: 68,
      division: 20,
    },
    lastAssessed: '2026-09-18T10:00:00Z',
    evidences: {
      paragraphReading: {
        skillId: 'paragraphReading',
        skillName: 'Paragraph Reading',
        status: 'developing',
        confidence: 72,
        evidenceSummary: 'Reads 3 out of 4 sentences correctly. Pauses at connected conjunctions.',
        nextAction: 'Guided short passage practice with audio assistance.',
      },
      subtraction: {
        skillId: 'subtraction',
        skillName: '2-Digit Subtraction',
        status: 'developing',
        confidence: 68,
        evidenceSummary: 'Solves simple subtraction without borrowing. Hesitates when borrowing across place values.',
        nextAction: 'Visual place value regrouping exercises.',
      },
    },
  },
  badges: [
    {
      id: 'badge-1',
      title: 'Letter Explorer',
      description: 'Recognized all alphabet letters fluently!',
      icon: '🔤',
      category: 'reading',
      isUnlocked: true,
      unlockedAt: '2026-09-10',
    },
    {
      id: 'badge-2',
      title: 'Word Builder',
      description: 'Mastered reading 50+ foundational words!',
      icon: '📖',
      category: 'reading',
      isUnlocked: true,
      unlockedAt: '2026-09-14',
    },
    {
      id: 'badge-3',
      title: 'Number Navigator',
      description: 'Recognizes numbers 1 to 99 with ease!',
      icon: '🔢',
      category: 'numeracy',
      isUnlocked: true,
      unlockedAt: '2026-09-12',
    },
    {
      id: 'badge-4',
      title: '5-Day Streak Hero',
      description: 'Practiced 5 days in a row!',
      icon: '🔥',
      category: 'streak',
      isUnlocked: true,
      unlockedAt: '2026-09-18',
    },
    {
      id: 'badge-5',
      title: 'Story Master',
      description: 'Read a full story and answered comprehension questions!',
      icon: '🏰',
      category: 'reading',
      isUnlocked: false,
    },
    {
      id: 'badge-6',
      title: 'Division Champion',
      description: 'Solved 3-digit by 1-digit division problems!',
      icon: '⚡',
      category: 'numeracy',
      isUnlocked: false,
    },
  ],
};

// Reading World Progression Stages (Matching AGENTS.md Section 6)
export function getReadingWorldStages(learner: Learner): WorldStage[] {
  return [
    {
      id: 'stage-r1',
      name: 'Letter Explorer',
      description: 'Identify basic letter sounds and symbols',
      icon: '🌱',
      pathway: 'reading',
      level: 'letter',
      status: 'mastered',
      progressPercent: 100,
      xpReward: 100,
    },
    {
      id: 'stage-r2',
      name: 'Word Builder',
      description: 'Recognize common 2-letter and 3-letter words',
      icon: '🔤',
      pathway: 'reading',
      level: 'word',
      status: 'mastered',
      progressPercent: 100,
      xpReward: 150,
    },
    {
      id: 'stage-r3',
      name: 'Sentence Navigator',
      description: 'Read short 4-word sentences with fluency',
      icon: '📖',
      pathway: 'reading',
      level: 'paragraph',
      status: 'mastered',
      progressPercent: 100,
      xpReward: 200,
    },
    {
      id: 'stage-r4',
      name: 'Paragraph Explorer',
      description: 'Read connected text (4 simple sentences)',
      icon: '📚',
      pathway: 'reading',
      level: 'paragraph',
      status: 'current',
      progressPercent: 72,
      xpReward: 250,
    },
    {
      id: 'stage-r5',
      name: 'Story Master',
      description: 'Read 7-10 sentence story with full comprehension',
      icon: '🏰',
      pathway: 'reading',
      level: 'story',
      status: 'locked',
      progressPercent: 0,
      xpReward: 300,
    },
  ];
}

// Numeracy World Progression Stages (Matching AGENTS.md Section 6)
export function getNumeracyWorldStages(learner: Learner): WorldStage[] {
  return [
    {
      id: 'stage-n1',
      name: 'Number Explorer',
      description: 'Recognize numbers from 1 to 9',
      icon: '1️⃣',
      pathway: 'numeracy',
      level: 'number_1_9',
      status: 'mastered',
      progressPercent: 100,
      xpReward: 100,
    },
    {
      id: 'stage-n2',
      name: 'Number Navigator',
      description: 'Recognize 2-digit numbers (11 to 99)',
      icon: '🔢',
      pathway: 'numeracy',
      level: 'number_11_99',
      status: 'mastered',
      progressPercent: 100,
      xpReward: 150,
    },
    {
      id: 'stage-n3',
      name: 'Subtraction Solver',
      description: 'Solve 2-digit subtraction with borrowing',
      icon: '➖',
      pathway: 'numeracy',
      level: 'subtraction',
      status: 'current',
      progressPercent: 68,
      xpReward: 250,
    },
    {
      id: 'stage-n4',
      name: 'Division Master',
      description: 'Solve 3-digit by 1-digit division problems',
      icon: '➗',
      pathway: 'numeracy',
      level: 'division',
      status: 'locked',
      progressPercent: 0,
      xpReward: 300,
    },
  ];
}

// Sample Practice Questions for Student Practice Zone
export const MOCK_PRACTICE_QUESTIONS: PracticeQuestion[] = [
  {
    id: 'pq-1',
    pathway: 'reading',
    level: 'paragraph',
    content: 'The big brown dog jumped over the fence.',
    audioPrompt: 'Read this sentence out loud: The big brown dog jumped over the fence.',
    options: ['The dog jumped over the fence.', 'The cat sat on the mat.', 'The bird flew in the sky.'],
    correctAnswer: 'The dog jumped over the fence.',
    explanation: 'Awesome reading! You identified what the dog did correctly! 🌟',
    xp: 20,
  },
  {
    id: 'pq-2',
    pathway: 'reading',
    level: 'paragraph',
    content: 'Meena likes to play with her red ball in the park.',
    audioPrompt: 'What does Meena like to play with?',
    options: ['Her red ball', 'A blue bicycle', 'A green kite'],
    correctAnswer: 'Her red ball',
    explanation: 'Superb! Meena plays with her red ball! 🎈',
    xp: 20,
  },
  {
    id: 'pq-3',
    pathway: 'numeracy',
    level: 'subtraction',
    content: 'What is 54 - 27 ?',
    audioPrompt: 'Subtract 27 from 54.',
    options: ['27', '37', '17'],
    correctAnswer: '27',
    explanation: 'Fantastic math skills! 54 minus 27 equals 27! 🧮',
    xp: 25,
  },
  {
    id: 'pq-4',
    pathway: 'numeracy',
    level: 'subtraction',
    content: 'In 472, what is the place value of 7?',
    audioPrompt: 'What is the place value of 7 in 472?',
    options: ['70 (Tens)', '700 (Hundreds)', '7 (Ones)'],
    correctAnswer: '70 (Tens)',
    explanation: 'Brilliant! The 7 is in the Tens place, so its value is 70! 🔢',
    xp: 25,
  },
];
